#!/bin/bash

run() {
  exec=$1
  printf "\x1b[38;5;104m -- ${exec}\x1b[39m\n"
  eval ${exec}
}


say () {
  say=$1
  printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

say "Install rs-server"
run "mkdir -p /opt/remoteShackPTT/bin"
run "cp rs-input /opt/remoteShackPTT/bin && chmod +x /opt/remoteShackPTT/bin/rs-input"

say "Install rs-client"
run "cp rs-input /opt/remoteShackPTT/bin && chmod +x /opt/remoteShackPTT/bin/rs-input"
