#!/bin/bash

say () {
 say=$1
 printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

say "Install Service file"
cat <<EOF > /etc/systemd/system/remoteShackPTT.service
[Unit]
Description=remoteShackPTT
Requires=networking.service
After=networking.service

[Service]
Type=simple
StandardInput=tty-force
ExecStart=/bin/bash -c "/opt/remoteShackPTT/rs-server 2>&1"
Restart=always

[Install]
WantedBy=multi-user.target
EOF
