#!/bin/bash

run() {
  exec=$1
  printf "\x1b[38;5;104m -- ${exec}\x1b[39m\n"
  eval ${exec}
}

say () {
 say=$1
 printf "\x1b[38;5;220m${say}\x1b[38;5;255m\n"
}

say "Install Service file"
cat <<EOF > /etc/systemd/system/remoteShackPTT.service
[Unit]
Description=remoteShackPTT
Requires=networking.service
After=networking.service

[Service]
Type=simple
StandardInput=tty-force
ExecStart=/bin/bash -c "/opt/remoteShackPTT/binrs-server 2>&1"
Restart=always

[Install]
WantedBy=multi-user.target
EOF

run "systemctl daemon-reload"
run "systemctl restart remoteShackPTT"
